smsproj/urls.py
from django.contrib import admin
from django.urls import path
from smsapp import views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home, name="home"),
    path('', views.home, name="home"),
    path('newrecord/', views.createrecord, name="createrecord"),
    path('recordlist/', views.recordlist, name="recordlist"),
    path('grouplist/', views.grouplist, name="grouplist"),
    path('newbmessagecat/', views.createbmessagecat, name="createbmessagecat"),
    path('newbmessagedis/', views.createbmessagedis, name="createbmessagedis"),
    path('newbmessageall/', views.createbmessageall, name="createbmessageall"),
    path('newgroup/', views.creategroup, name="creategroup"),
    path('newmesstemp/', views.messtemp, name="messtemp"),
    path('templatelist/', views.templatelist, name="templatelist"),
    path('deliverylist/', views.deliverylist, name="deliverylist"),
    path('bcriteria/', views.bcriteria, name="bcriteria"),

    path('ajax/load-grades/', views.load_grades, name='ajax_load_grades'),
    path('ajax/validate_empnumber/', views.validate_empnumber, name='validate_empnumber'),
    
    path('updaterecord/<str:pk>/', views.updaterecord, name="updaterecord"),
    path('recordsupdate/<str:pk>/', views.records_update, name="recordsupdate"),
    path('record_create/', views.record_create, name="record_create"),
    path('trying/', views.trying, name='trying'),
    
    
    
    
    #paths for the users app
    path('register/', user_views.register, name="register"),
    path('login/', user_views.loginpage, name="login"),
    path('logout/', user_views.logoutuser, name="logoutuser"),
]

admin.site.site_header = "Welcome to Western North Regional Health Directorate SMS Portal"
admin.site.site_title = "WN-RHD Admin Portal"
admin.site.index_title = "WNR-SMSApp Admin"

smsapp/models.py
from django.db import models

from datetime import datetime    


# Create your models here.
class region(models.Model):
	regionName = models.CharField(max_length = 100)
	
	def __str__(self):
		return self.regionName
	
class district(models.Model):
	districtName = models.CharField(max_length= 100)
	region = models.ForeignKey(region, null=True, on_delete=models.SET_NULL)
	
	def __str__(self):
		return self.districtName
	
class subdistrict(models.Model):
	subdistrictName = models.CharField(max_length=100)
	district = models.ForeignKey(district, null=True, on_delete=models.SET_NULL)
	
	def __str__(self):
		return self.subdistrictName
	
class bmc(models.Model):
	bmcName = models.CharField(max_length=100)
	subdistrict = models.ForeignKey(subdistrict, null=True, on_delete=models.SET_NULL)
	
	class Meta:
		ordering = ('bmcName',)
	
	def __str__(self):
		return self.bmcName
		

	
class group(models.Model):
	
	groupName = models.CharField(max_length=100)
	
	def __str__(self):
		return self.groupName


	
class unit(models.Model):
	unit = models.CharField(max_length=100)
	
	def __str__(self):
		return self.unit


class category(models.Model):
	catName = models.CharField(max_length=100)
	
	class Meta:
		verbose_name_plural='Categories'
		
	def __str__(self):
		return self.catName
		
class grade(models.Model):
	grade = models.CharField(max_length=100)
	category = models.ForeignKey(category, null=True, on_delete=models.SET_NULL)
	
	class Meta:
		ordering = ('grade',)
	
	def __str__(self):
		return self.grade 

class records(models.Model):
	GENDER = (
			 ('Male', 'Male'),
			 ('Female', 'Female'),
			
			 )
	TITLE = (
			 ('Mr.', 'Mr.'),
			 ('Mrs.', 'Mrs.'),
			 ('Miss.', 'Miss'),
			 ('Dr.', 'Dr.'),
			
			 )
			 		 
	MARITAL_STATUS = (
			 ('Single', 'Single'),
			 ('Married', 'Married'),
			 ('Divorced', 'Divorced'),
			 ('Widowed', 'Widowed'),
			
			 )
			 
	RELIGION = (
			 ('Christian', 'Christian'),
			 ('Muslim', 'Muslim'),
			 ('Other', 'Other'),
			
			 )
			 
	STATUS = (
			 ('Active', 'Active'),
			 ('Inactive', 'Inactive'),
			
			 )
	
	EmpNumber = models.CharField(max_length=15,primary_key=True, verbose_name='Employment Number')
	Title = models.CharField(max_length=11, choices=TITLE, default=TITLE[0][0],null=True, blank=True)
	FirstName = models.CharField(max_length=50, verbose_name='First Name')
	LastName = models.CharField(max_length=50, verbose_name='Last Name')
	OtherName = models.CharField(max_length=50, verbose_name='Other Name', null=True, blank=True)
	Gender = models.CharField(max_length=10, choices=GENDER)
	DOB = models.DateField(verbose_name='Date of Birth')
	MaritalStatus = models.CharField(max_length=10, choices=MARITAL_STATUS, verbose_name='Marital Status', null=True, blank=True)
	Religion = models.CharField(max_length=10, choices=RELIGION, blank=True)
	OfficialEmail= models.CharField(max_length=50,verbose_name='Official Email', unique=True, null=True, blank=True)
	PersonalEmail= models.CharField(max_length=50, verbose_name='Personal Email',null=True, blank=True)
	Mobile = models.CharField(max_length=10, verbose_name='1st Mobile', unique=True)
	Mobile1 = models.CharField(max_length=10,verbose_name='2nd Mobile', null=True, blank=True)
	FirstAppDate = models.DateField(verbose_name='First Appointment Date')
	AssumptionDutyDate= models.DateField(verbose_name='Date of Assumption of Duty')
	category = models.ForeignKey(category, null=True, verbose_name='Category', on_delete=models.SET_NULL)
	grade = models.ForeignKey(grade, null=True, on_delete=models.SET_NULL)
	bmc = models.ForeignKey(bmc, null=True, verbose_name='BMC', on_delete=models.SET_NULL)
	unit = models.ForeignKey(unit, null=True, on_delete=models.SET_NULL, blank=True)
	status = models.CharField(max_length=10, choices=STATUS, default=STATUS[0][0], null=True)
	date_created = models.DateTimeField(default=datetime.now, null=True)
	date_updated = models.DateTimeField(auto_now=True, null=True)
	
	class Meta:
		verbose_name_plural = 'records'
	
	def __str__(self):
		return self.FirstName




class broadcastmessagedis(models.Model):
	
	
	Subject=models.CharField(max_length=50)
	Content=models.CharField(max_length=400)
	district=models.ForeignKey(district, null=True, on_delete=models.SET_NULL)
	
	
	class Meta:
		verbose_name_plural='District-based Broadcast Messages'
	
	def __str__(self):
		return self.Subject


class broadcastmessagecat(models.Model):
	
	
	Subject=models.CharField(max_length=50)
	Content=models.CharField(max_length=400)
	category=models.ManyToManyField(category)
	
	
	class Meta:
		verbose_name_plural='Category-based Broadcast Messages'
	
	def __str__(self):
		return self.Subject

class broadcastmessageall(models.Model):
	Subject=models.CharField(max_length=50)
	Content=models.CharField(max_length=400)
	
	class Meta:
		verbose_name_plural='Broadcast Messages to all'
	
	def __str__(self):
		return self.Subject

class delivery(models.Model):
	sms_status = models.CharField(max_length=50)
	smstype = models.CharField(max_length=50)
	total_sent = models.CharField(max_length=50)
	total_rejected = models.CharField(max_length=50)
	recipient=models.CharField(max_length=50)
	credit_used = models.CharField(max_length=50)
	credit_left = models.CharField(max_length=50)
	date_created = models.DateTimeField(auto_now_add=True)
	
	class Meta:
		verbose_name_plural = 'Deliveries'
	
	def __str__(self):
		return self.sms_status

	

smsapp/views.py
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils import timezone
from django.contrib import messages
from smsapp.models import *
from smsapp.forms import *
import requests
import json
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
# Create your views here.
#

def record_create(request):
    form = RecordsForm()
    context = {'form': form}
    html_form = render_to_string('smsapp/partial_record_create.html',
        context,
        request=request,
    )
    return JsonResponse({'html_form': html_form})


@login_required
def load_grades(request):
    category_id = request.GET.get('category_id')
    grades = grade.objects.filter(category_id=category_id).order_by('grade')
    
    return render(request, 'smsapp/grades_dropdown_list_options.html', {'grades': grades})

@login_required
def validate_empnumber(request):
    EmpNumber = request.GET.get('EmpNumber')
    data = {
        'is_taken': records.objects.filter(EmpNumber__iexact=EmpNumber).exists()
    }
    print(data)
    return JsonResponse(data)


def records_update(request):
    EmpNumber = request.GET.get('EmpNumber')
    recod = records.objects.filter(Empnumber__iexact=Empnumber)
    
    return JsonResponse(recod)


@login_required
def home(request):
	today = timezone.now().date()
	alrecods=records.objects.all()
	recods=records.objects.all().order_by('-date_created')[:5][::-1]
	deliveries=delivery.objects.all().order_by('-date_created')[:5]
	aldeliveries=delivery.objects.all()
	act_recods=records.objects.filter(status='Active')
	inact_recods=records.objects.filter(status='Inactive')
	
	bdaysms=delivery.objects.filter(smstype='Birthday').count()
	annisms=delivery.objects.filter(smstype='Anniversary').count()
	bsms=delivery.objects.filter(smstype='Broadcast').count()
	welsms=delivery.objects.filter(smstype='Welcome').count()
	
	recodsnum=alrecods.count()
	activenum=act_recods.count()
	inactivenum=inact_recods.count()
	
	context={
		'recods':recods,
		'recodsnum':recodsnum,
		'activenum':activenum, 
		'inactivenum':inactivenum, 
		'deliveries':deliveries,
		'aldeliveries':aldeliveries,
		'alrecods':alrecods,
		'bdaysms': bdaysms,
		'annisms': annisms,
		'bsms': bsms,
		'welsms': welsms,
		} 
	return render(request, 'smsapp/dashboard.html', context)


@login_required
def createrecord(request):
	"""form page for creating records"""

	fm = RecordsForm()
	if request.method == 'POST':
		fm = RecordsForm(request.POST)
		
		if fm.is_valid():
			fm.save()
			messages.success(request, "Record successfully created!")

			fon=request.POST.get('Mobile')
			titlename=request.POST.get('Title')
			firstname=request.POST.get('FirstName')
			lastname=request.POST.get('LastName')
			emaill=request.POST.get('OfficialEmail')
			dateOB=request.POST.get('DOB')
			
			
			endPoint = 'https://api.mnotify.com/api/sms/quick'
			apiKey = 'rT5L5lrhhoCaP0BfKlSU9dNh6Vqp5RFwLKhQ6I8n7KyWL'
			data = {
				'recipient[]': fon,
				'sender': 'HR WNRHD',
				'message': 'Dear %s, You are welcome to the Western North Regional Health Directorate SMS platform. Thank you for joining this great health family.\n\nRSVP: 0204912857' % firstname,
				'is_schedule': False,
				'schedule_date': ''
				}
			url = endPoint + '?key=' + apiKey
			response = requests.post(url, data)
			data = response.json()
			
			bstatus=json.dumps(data['status'])
			bsmstype='Welcome'
			btotalsent=json.dumps(data["summary"]["total_sent"])
			btotalrejected=json.dumps(data["summary"]["total_rejected"])
			brecipient=json.dumps(data["summary"]["numbers_sent"])
			bcreditused=json.dumps(data["summary"]["credit_used"])
			bcreditleft=json.dumps(data["summary"]["credit_left"])
			
			delivery_instance = delivery(
										sms_status=bstatus, 
										smstype=bsmstype, 
										total_sent=btotalsent, 
										total_rejected=btotalrejected, 
										recipient=brecipient, 
										credit_used=bcreditused, 
										credit_left=bcreditleft
										)
			delivery_instance.save()
			return redirect('/home')
		
	context = {'fm':fm}
	
	return render(request, 'smsapp/recordfrm.html', context)

def updaterecord(request, pk):
	"""form page for creating orders"""
	record = records.objects.get(EmpNumber=pk)
	fm = RecordsForm(instance=record)
	
	if request.method == 'POST':
		fm = RecordsForm(request.POST or None, instance=record)
		if fm.is_valid():
			fm.save()
			messages.success(request, "Record successfully updated!")
			return redirect('/recordlist')
	else:
		fm = RecordsForm(instance=record)
	
	context = {'fm':fm}
	return render (request, 'smsapp/recordupdatefrm.html', context)


@login_required
def creategroup(request):
	
	fm = GroupForm()
	if request.method == 'POST':
		fm = GroupForm(request.POST)
		
		if fm.is_valid():
			fm.save()
		
		
		return redirect('/grouplist')

	context = {'fm':fm}
	return render(request, 'smsapp/groupfrm.html', context)


@login_required
def bcriteria(request):
	crit=request.POST.get('criteria')
	if request.method == 'POST' and crit=='district':
		return redirect('/newbmessagedis')
	elif request.method =='POST' and crit=='category':
		return redirect('/newbmessagecat')
	elif request.method =='POST' and crit=='all':
		return redirect('/newbmessageall')
	
	
	
		
	context = {}
	return render(request, 'smsapp/bcriteria.html', context)




@login_required
def createbmessagedis(request):
	"""form page for creating records"""
	fm = BroadcastmessagedisForm()
	if request.method == 'POST':
		fm = BroadcastmessagedisForm(request.POST)
		dist=request.POST.get('district')
		
		dist_records=records.objects.filter(bmc__subdistrict__district=dist)
		
		cont=request.POST.get('Content')
		
		for recod in dist_records:
			endPoint = 'https://api.mnotify.com/api/sms/quick'
			apiKey = 'rT5L5lrhhoCaP0BfKlSU9dNh6Vqp5RFwLKhQ6I8n7KyWL'
			data = {
			   'recipient[]': [recod.Mobile],
			   'sender': 'HR WNRHD',
			   'message': cont,
			   'is_schedule': False,
			   'schedule_date': ''
			}
			url = endPoint + '?key=' + apiKey
			response = requests.post(url, data)
			data = response.json()
			
			bstatus=json.dumps(data['status'])
			bsmstype='Broadcast'
			btotalsent=json.dumps(data["summary"]["total_sent"])
			btotalrejected=json.dumps(data["summary"]["total_rejected"])
			brecipient=json.dumps(data["summary"]["numbers_sent"])
			bcreditused=json.dumps(data["summary"]["credit_used"])
			bcreditleft=json.dumps(data["summary"]["credit_left"])
			
			delivery_instance = delivery(
									sms_status=bstatus, 
									smstype=bsmstype, 
									total_sent=btotalsent, 
									total_rejected=btotalrejected, 
									recipient=brecipient, 
									credit_used=bcreditused, 
									credit_left=bcreditleft
									)
			delivery_instance.save()
			
			return redirect('/home')
	
	context = {'fm':fm}
	
	return render(request, 'smsapp/bcmessagedisfrm.html', context)

@login_required
def createbmessagecat(request):
	"""form page for creating records"""
	fm = BroadcastmessagecatForm()
	if request.method == 'POST':
		fm = BroadcastmessagecatForm(request.POST)
		cat=request.POST.get('category')
		
		cat_records=records.objects.filter(category=cat)
		
		cont=request.POST.get('Content')
		
		for recod in cat_records:
			endPoint = 'https://api.mnotify.com/api/sms/quick'
			apiKey = 'rT5L5lrhhoCaP0BfKlSU9dNh6Vqp5RFwLKhQ6I8n7KyWL'
			data = {
			   'recipient[]': [recod.Mobile],
			   'sender': 'HR WNRHD',
			   'message': cont,
			   'is_schedule': False,
			   'schedule_date': ''
			}
			url = endPoint + '?key=' + apiKey
			response = requests.post(url, data)
			data = response.json()
			
			bstatus=json.dumps(data['status'])
			bsmstype='Broadcast'
			btotalsent=json.dumps(data["summary"]["total_sent"])
			btotalrejected=json.dumps(data["summary"]["total_rejected"])
			brecipient=json.dumps(data["summary"]["numbers_sent"])
			bcreditused=json.dumps(data["summary"]["credit_used"])
			bcreditleft=json.dumps(data["summary"]["credit_left"])
			
			delivery_instance = delivery(
									sms_status=bstatus, 
									smstype=bsmstype, 
									total_sent=btotalsent, 
									total_rejected=btotalrejected, 
									recipient=brecipient, 
									credit_used=bcreditused, 
									credit_left=bcreditleft
									)
			delivery_instance.save()
			
			return redirect('/home')
	
	context = {'fm':fm}
	
	return render(request, 'smsapp/bcmessagecatfrm.html', context)


@login_required
def createbmessageall(request):
	"""form page for creating records"""
	alrecods=records.objects.all()
	recodsnum=alrecods.count()
	
	
	fm = BroadcastmessageallForm()
	if request.method == 'POST':
		fm = BroadcastmessageallForm(request.POST)
		cat=request.POST.get('category')
		
		br_records= alrecods
		
		cont=request.POST.get('Content')
		
		for recod in br_records:
			endPoint = 'https://api.mnotify.com/api/sms/quick'
			apiKey = 'rT5L5lrhhoCaP0BfKlSU9dNh6Vqp5RFwLKhQ6I8n7KyWL'
			data = {
			   'recipient[]': [recod.Mobile],
			   'sender': 'HR WNRHD',
			   'message': cont,
			   'is_schedule': False,
			   'schedule_date': ''
			}
			url = endPoint + '?key=' + apiKey
			response = requests.post(url, data)
			data = response.json()
			
			bstatus=json.dumps(data['status'])
			bsmstype='Broadcast'
			btotalsent=json.dumps(data["summary"]["total_sent"])
			btotalrejected=json.dumps(data["summary"]["total_rejected"])
			brecipient=json.dumps(data["summary"]["numbers_sent"])
			bcreditused=json.dumps(data["summary"]["credit_used"])
			bcreditleft=json.dumps(data["summary"]["credit_left"])
			
			delivery_instance = delivery(
									sms_status=bstatus, 
									smstype=bsmstype, 
									total_sent=btotalsent, 
									total_rejected=btotalrejected, 
									recipient=brecipient, 
									credit_used=bcreditused, 
									credit_left=bcreditleft
									)
			delivery_instance.save()
			
			return redirect('/home')
	
	context = {'fm':fm, 'recodsnum':recodsnum}
	
	return render(request, 'smsapp/bcmessageallfrm.html', context)

smsapp/templates/smsapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %} <title>Base Template</title> {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
<!-- CDN links -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  
  
<!--links to static files-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/sticky-footer-navbar.css' %}">
  
  

</head>

<body id="index" class="home">

	<details>
  <summary>Notification Desk</summary>
  <p><h2>Wear a mask, Clean your hands, Keep a safe distance</h2></p>
	</details>


<header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">
			<img src="{% static 'images/IMG.jpeg' %}" alt="Logo" style="width:40px;">
			WN-RHD
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
				<a class="nav-link" href="{% url 'recordlist' %}">Registrations</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'deliverylist' %}">Sent Notifications</a>
			</li>
			
          </ul>
          
          {% if user.is_authenticated %}
		  <span>
			  <li class="nav-item">
				<a class="nav-link" href=""><b>Hello, {{request.user}}</b></a>
			  </li>
		  </span>
		  <span>
			   <li class="nav-item">
				<a class="nav-link" href="{% url 'logoutuser' %}"><b>Logout</b></a>
			  </li>
		  </span>
		  {% else %}
		   <span>
			   <li class="nav-item">
				<a class="nav-link" href="{% url 'login' %}"><b>Login</b></a>
			  </li>
		  </span>
		  {%  endif %}
        </div>
        
        
      </nav>
</header>
<main role="main" class="container">
	<div class="row">
		<div class="col-md-12">
			{% if messages %}
			{% for message in messages %}
			<div class="alert alert-{{message.tags}}">
				{{ message }}
			</div>
			{% endfor %}
			{% endif %}
		</div>
	</div>
</main>
{% block content %}
<br><br>


{% endblock %}






</body>



<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

 <script>
    $("#id_category").change(function () {
      const url = $("#recordForm").attr("data-grades-url");  // get the url of the `load_cities` view
      const categoryId = $(this).val();  // get the selected country ID from the HTML input
      
      
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load_grades/)
        data: {
          'category_id': categoryId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          console.log(data);
          $("#id_grade").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
 </script>
 
<script>
	$("#id_EmpNumber").change(function () {
		const empnumber = $(this).val();
		const url = $("#recordForm").attr("empnumbvalidate-url");
		console.log( $(this).val() );

		$.ajax({
           url: url,
           data: {
			'EmpNumber': empnumber       // add the country id to the GET parameters
		   },
		   
		   success: function (data) {
			   if (data.is_taken){
				   alert("A record with this Employment Number already exists.")
			   }
			}
        });
    });
</script>
 
<script>
    $(".js-create-record").click(function () {
      $.ajax({                       // initialize an AJAX request
        url: "{% url 'record_create' %}",                    // set the url of the request (= localhost:8000/hr/ajax/load_grades/)
		type: 'get',
		dataType: 'json',
		beforeSend: function(){
			$("#modal-records").modal("show");
		},
        success: function (data) {
        $("#modal-records .modal-content").html(data.html_form);
      	}
      });

    });
 </script>

 <noscript>
         Sorry...JavaScript is needed to go ahead.
 </noscript>

</html>

smsapp/templates/smsapp/bcmessageallfrm.html
{% extends 'smsapp/base.html' %}

{% load static %}

{% block title %} <title>Broadcast Notification</title> {% endblock %}

{% block content %}



<style>
.myform {
  margin: 70px 400px;
}
</style>

  




<div class="myform">	
<div class="jumbotron">
	<b>Hello, {{request.user}}</b> <br>
	<p>You are about to send this message to <span style="color:blue">{{ recodsnum }} worker(s)</span>  registered on this system.</p>
	<p>If you want to continue,complete the fields below and click 'Send Broadcast'</p>
	<br>
<form action="" method="POST">
  {% csrf_token %}
	
  {{fm.as_p}}
  <br>
  <button type="submit" class="btn btn-primary">Send Broadcast</button>
  <a class="btn btn-primary" href="{% url 'home' %}">Cancel</a>
  
  <p><span style="color:maroon">After clicking 'Send Broadcast', do not leave the page until all messages are sent.</span></p>
</form>
					
					
					
</div>
</div>

{% endblock %}

smsapp/templates/smsapp/bcmessagecatfrm.html
{% extends 'smsapp/base.html' %}

{% load static %}

{% block title %} <title>Broadcast Message Form</title> {% endblock %}





{% block content %}

<style>
.myform {
  margin: 70px 450px;
}
</style>


<div class="myform">
<div class="jumbotron">
	<h3>Create a Broadcast Message</h3>
	<br>
<form action="" method="POST">
  {% csrf_token %}
	
  {{fm.as_p}}
  <br>
  <button type="submit" class="btn btn-primary">Send Broadcast</button>
  <a class="btn btn-primary" href="{% url 'home' %}">Cancel</a>
</form>
</div>
</div>

{% endblock %}

smsapp/templates/smsapp/bcmessagedisfrm.html
{% extends 'smsapp/base.html' %}

{% load static %}

{% block title %} <title>Broadcast Message Form</title> {% endblock %}





{% block content %}

<style>
.myform {
  margin: 70px 450px;
}
</style>


<div class="myform">
<div class="jumbotron">
	<h3>Create a Broadcast Message</h3>
	<br>
<form action="" method="POST">
  {% csrf_token %}
	
  {{fm.as_p}}
  <br>
  <button type="submit" class="btn btn-primary">Send Broadcast</button>
  <a class="btn btn-primary" href="{% url 'home' %}">Cancel</a>
</form>
</div>
</div>

{% endblock %}

smsapp/templates/smsapp/bcmessagefrm.html
{% extends 'smsapp/base.html' %}

{% load static %}

{% block title %} <title>Broadcast Message Form</title> {% endblock %}





{% block content %}

<style>
.myform {
  margin: 70px 450px;
}
</style>


<div class="myform">
<div class="jumbotron">
	<h3>Create a Broadcast Message</h3>
	<br>
<form action="" method="POST">
  {% csrf_token %}
	
  {{fm.as_p}}
  <button type="submit" class="btn btn-primary">Send Broadcast</button>
  <a class="btn btn-primary" href="{% url 'home' %}">Cancel</a>
</form>
</div>
</div>

{% endblock %}

smsapp/templates/smsapp/grades_dropdown_list_options.html
<option value=""></option>
{% for gr in grades %}
<option value="{{ gr.pk }}">{{ gr.grade }}</option>
{% endfor %}

smsapp/templates/smsapp/messtempfrm.html
{% extends 'smsapp/base.html' %}

{% load static %}

{% block title %} <title>Message Template Form</title> {% endblock %}





{% block content %}

<style>
.myform {
  margin: 70px 450px;
}
</style>


<div class="myform">
<div class="jumbotron">
<form action="" method="POST">
  {% csrf_token %}
	
  {{fm.as_p}}
  <button type="submit" class="btn btn-primary">Save as Template</button>
  <a class="btn btn-primary" href="{% url 'grouplist' %}">Cancel</a>
</form>
</div>
</div>

{% endblock %}